version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"